import type { UnvanDesign } from '../tipler';

export type UnvanPreset = {
  id: string;
  label: string;
  design: UnvanDesign;
};

const base = (partial: Partial<UnvanDesign> & Pick<UnvanDesign, 'backgroundColor' | 'textColor'>): UnvanDesign => ({
  shape: 'SOFT_PILL',
  backgroundType: 'SOLID',
  backgroundColor2: null,
  backgroundColor3: null,
  gradientDirection: 'LEFT_RIGHT',
  borderEnabled: false,
  borderColor: '#FFFFFF',
  borderWidth: 1,
  borderOpacity: 1,
  cornerRadius: null,
  glowEnabled: false,
  glowColor: '#A78BFA',
  glowIntensity: 'off',
  animationType: 'NONE',
  fontWeight: 'semibold',
  iconType: 'library',
  iconValue: 'star',
  iconPosition: 'LEFT',
  size: 'NORMAL',
  paddingH: 8,
  paddingV: 3,
  ...partial,
});

/** Admin tasarımcı için hazır paletler — sunucu seed değil, UI shortcut */
export const UNVAN_PRESETLERI: UnvanPreset[] = [
  {
    id: 'tamuso_pink',
    label: 'Tamuso Pink',
    design: base({
      shape: 'SOFT_PILL',
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#EC4899',
      backgroundColor2: '#9D174D',
      textColor: '#FCE7F3',
      iconValue: 'heart',
      glowEnabled: true,
      glowColor: '#EC4899',
      glowIntensity: 'soft',
    }),
  },
  {
    id: 'royal_gold',
    label: 'Royal Gold',
    design: base({
      shape: 'PILL',
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#F6C453',
      backgroundColor2: '#B98217',
      textColor: '#FFF4CE',
      borderEnabled: true,
      borderColor: '#FFD976',
      borderOpacity: 0.9,
      iconValue: 'crown',
      glowEnabled: true,
      glowColor: '#F6C453',
      glowIntensity: 'soft',
      animationType: 'SOFT_GLOW',
    }),
  },
  {
    id: 'creator_purple',
    label: 'Creator Purple',
    design: base({
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#A78BFA',
      backgroundColor2: '#5B21B6',
      textColor: '#F5F3FF',
      iconValue: 'creator',
      glowEnabled: true,
      glowColor: '#8B5CF6',
      glowIntensity: 'soft',
    }),
  },
  {
    id: 'verified_blue',
    label: 'Verified Blue',
    design: base({
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#38BDF8',
      backgroundColor2: '#0369A1',
      textColor: '#E0F2FE',
      iconValue: 'verified',
      borderEnabled: true,
      borderColor: '#7DD3FC',
      borderOpacity: 0.45,
    }),
  },
  {
    id: 'moderator_violet',
    label: 'Moderator Violet',
    design: base({
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#7C3AED',
      backgroundColor2: '#4C1D95',
      textColor: '#EDE9FE',
      iconValue: 'shield',
      borderEnabled: true,
      borderColor: '#A78BFA',
      borderOpacity: 0.35,
      glowEnabled: true,
      glowColor: '#8B5CF6',
      glowIntensity: 'soft',
    }),
  },
  {
    id: 'vip_diamond',
    label: 'VIP Diamond',
    design: base({
      shape: 'PILL',
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#67E8F9',
      backgroundColor2: '#0891B2',
      gradientDirection: 'DIAGONAL',
      textColor: '#ECFEFF',
      borderEnabled: true,
      borderColor: '#A5F3FC',
      borderOpacity: 0.5,
      iconValue: 'diamond',
      fontWeight: 'bold',
      glowEnabled: true,
      glowColor: '#22D3EE',
      glowIntensity: 'medium',
      animationType: 'SHIMMER',
    }),
  },
  {
    id: 'neon',
    label: 'Neon',
    design: base({
      shape: 'CAPSULE',
      backgroundType: 'SOLID',
      backgroundColor: '#0F172A',
      textColor: '#4ADE80',
      borderEnabled: true,
      borderColor: '#22C55E',
      borderOpacity: 0.85,
      iconValue: 'sparkles',
      glowEnabled: true,
      glowColor: '#22C55E',
      glowIntensity: 'strong',
      animationType: 'SOFT_GLOW',
    }),
  },
  {
    id: 'glass',
    label: 'Glass',
    design: base({
      shape: 'SOFT_PILL',
      backgroundType: 'GLASS',
      backgroundColor: 'rgba(255,255,255,0.12)',
      textColor: '#F8FAFC',
      borderEnabled: true,
      borderColor: 'rgba(255,255,255,0.28)',
      borderOpacity: 0.7,
      iconValue: 'star',
    }),
  },
  {
    id: 'minimal',
    label: 'Minimal',
    design: base({
      shape: 'MINIMAL',
      backgroundType: 'TRANSPARENT',
      backgroundColor: 'transparent',
      textColor: '#E2E8F0',
      borderEnabled: true,
      borderColor: 'rgba(226,232,240,0.35)',
      borderOpacity: 0.6,
      iconType: 'none',
      iconValue: '',
      fontWeight: 'medium',
      paddingH: 6,
      paddingV: 2,
      size: 'COMPACT',
    }),
  },
  {
    id: 'dark_premium',
    label: 'Dark Premium',
    design: base({
      shape: 'ROUNDED_RECT',
      backgroundType: 'LINEAR_GRADIENT',
      backgroundColor: '#1E1B2E',
      backgroundColor2: '#0B0A12',
      textColor: '#F5D0FE',
      borderEnabled: true,
      borderColor: '#C084FC',
      borderOpacity: 0.4,
      iconValue: 'flame',
      glowEnabled: true,
      glowColor: '#A855F7',
      glowIntensity: 'medium',
      animationType: 'GRADIENT_SHIFT',
    }),
  },
];

export function UnvanPresetAl(id: string): UnvanPreset | null {
  return UNVAN_PRESETLERI.find((p) => p.id === id) ?? null;
}
