insert into public.geo_countries (code, name, is_active, profile_enabled, sort_order, league_enabled)
values
('CU','Cuba',true,false,51,true),
('CV','Cabo Verde',true,false,52,true),
('CW','Curacao',true,false,53,true),
('CX','Christmas Island',true,false,54,true),
('CY','Cyprus',true,false,55,true),
('CZ','Czechia',true,false,56,true),
('DE','Germany',true,false,57,true),
('DJ','Djibouti',true,false,58,true),
('DK','Denmark',true,false,59,true),
('DM','Dominica',true,false,60,true),
('DO','Dominican Republic',true,false,61,true),
('DZ','Algeria',true,false,62,true),
('EC','Ecuador',true,false,63,true),
('EE','Estonia',true,false,64,true),
('EG','Egypt',true,false,65,true),
('EH','Western Sahara',true,false,66,true),
('ER','Eritrea',true,false,67,true),
('ES','Spain',true,false,68,true),
('ET','Ethiopia',true,false,69,true),
('FI','Finland',true,false,70,true),
('FJ','Fiji',true,false,71,true),
('FK','Falkland Islands',true,false,72,true),
('FM','Micronesia',true,false,73,true),
('FO','Faroe Islands',true,false,74,true),
('FR','France',true,false,75,true),
('GA','Gabon',true,false,76,true),
('GB','United Kingdom',true,false,77,true),
('GD','Grenada',true,false,78,true),
('GE','Georgia',true,false,79,true),
('GF','French Guiana',true,false,80,true),
('GG','Guernsey',true,false,81,true),
('GH','Ghana',true,false,82,true),
('GI','Gibraltar',true,false,83,true),
('GL','Greenland',true,false,84,true),
('GM','Gambia',true,false,85,true),
('GN','Guinea',true,false,86,true),
('GP','Guadeloupe',true,false,87,true),
('GQ','Equatorial Guinea',true,false,88,true),
('GR','Greece',true,false,89,true),
('GS','South Georgia',true,false,90,true),
('GT','Guatemala',true,false,91,true),
('GU','Guam',true,false,92,true),
('GW','Guinea-Bissau',true,false,93,true),
('GY','Guyana',true,false,94,true),
('HK','Hong Kong',true,false,95,true),
('HM','Heard Island',true,false,96,true),
('HN','Honduras',true,false,97,true),
('HR','Croatia',true,false,98,true),
('HT','Haiti',true,false,99,true),
('HU','Hungary',true,false,100,true)
on conflict (code) do update set
  is_active = true,
  league_enabled = true,
  sort_order = coalesce(public.geo_countries.sort_order, excluded.sort_order);
