insert into public.geo_countries (code, name, is_active, profile_enabled, sort_order, league_enabled)
values
('ID','Indonesia',true,false,101,true),
('IE','Ireland',true,false,102,true),
('IL','Israel',true,false,103,true),
('IM','Isle of Man',true,false,104,true),
('IN','India',true,false,105,true),
('IO','British Indian Ocean Territory',true,false,106,true),
('IQ','Iraq',true,false,107,true),
('IR','Iran',true,false,108,true),
('IS','Iceland',true,false,109,true),
('IT','Italy',true,false,110,true),
('JE','Jersey',true,false,111,true),
('JM','Jamaica',true,false,112,true),
('JO','Jordan',true,false,113,true),
('JP','Japan',true,false,114,true),
('KE','Kenya',true,false,115,true),
('KG','Kyrgyzstan',true,false,116,true),
('KH','Cambodia',true,false,117,true),
('KI','Kiribati',true,false,118,true),
('KM','Comoros',true,false,119,true),
('KN','Saint Kitts and Nevis',true,false,120,true),
('KP','North Korea',true,false,121,true),
('KR','South Korea',true,false,122,true),
('KW','Kuwait',true,false,123,true),
('KY','Cayman Islands',true,false,124,true),
('KZ','Kazakhstan',true,false,125,true),
('LA','Laos',true,false,126,true),
('LB','Lebanon',true,false,127,true),
('LC','Saint Lucia',true,false,128,true),
('LI','Liechtenstein',true,false,129,true),
('LK','Sri Lanka',true,false,130,true),
('LR','Liberia',true,false,131,true),
('LS','Lesotho',true,false,132,true),
('LT','Lithuania',true,false,133,true),
('LU','Luxembourg',true,false,134,true),
('LV','Latvia',true,false,135,true),
('LY','Libya',true,false,136,true),
('MA','Morocco',true,false,137,true),
('MC','Monaco',true,false,138,true),
('MD','Moldova',true,false,139,true),
('ME','Montenegro',true,false,140,true),
('MF','Saint Martin',true,false,141,true),
('MG','Madagascar',true,false,142,true),
('MH','Marshall Islands',true,false,143,true),
('MK','North Macedonia',true,false,144,true),
('ML','Mali',true,false,145,true),
('MM','Myanmar',true,false,146,true),
('MN','Mongolia',true,false,147,true),
('MO','Macao',true,false,148,true),
('MP','Northern Mariana Islands',true,false,149,true),
('MQ','Martinique',true,false,150,true)
on conflict (code) do update set
  is_active = true,
  league_enabled = true,
  sort_order = coalesce(public.geo_countries.sort_order, excluded.sort_order);
