insert into public.geo_countries (code, name, is_active, profile_enabled, sort_order, league_enabled)
values
('AD','Andorra',true,false,1,true),
,
('AE','United Arab Emirates',true,false,2,true),
,
('AF','Afghanistan',true,false,3,true),
,
('AG','Antigua and Barbuda',true,false,4,true),
,
('AI','Anguilla',true,false,5,true),
,
('AL','Albania',true,false,6,true),
,
('AM','Armenia',true,false,7,true),
,
('AO','Angola',true,false,8,true),
,
('AQ','Antarctica',true,false,9,true),
,
('AR','Argentina',true,false,10,true),
,
('AS','American Samoa',true,false,11,true),
,
('AT','Austria',true,false,12,true),
,
('AU','Australia',true,false,13,true),
,
('AW','Aruba',true,false,14,true),
,
('AX','Aland Islands',true,false,15,true),
,
('AZ','Azerbaijan',true,false,16,true),
,
('BA','Bosnia and Herzegovina',true,false,17,true),
,
('BB','Barbados',true,false,18,true),
,
('BD','Bangladesh',true,false,19,true),
,
('BE','Belgium',true,false,20,true),
,
('BF','Burkina Faso',true,false,21,true),
,
('BG','Bulgaria',true,false,22,true),
,
('BH','Bahrain',true,false,23,true),
,
('BI','Burundi',true,false,24,true),
,
('BJ','Benin',true,false,25,true),
,
('BL','Saint Barthelemy',true,false,26,true),
,
('BM','Bermuda',true,false,27,true),
,
('BN','Brunei',true,false,28,true),
,
('BO','Bolivia',true,false,29,true),
,
('BQ','Caribbean Netherlands',true,false,30,true),
,
('BR','Brazil',true,false,31,true),
,
('BS','Bahamas',true,false,32,true),
,
('BT','Bhutan',true,false,33,true),
,
('BV','Bouvet Island',true,false,34,true),
,
('BW','Botswana',true,false,35,true),
,
('BY','Belarus',true,false,36,true),
,
('BZ','Belize',true,false,37,true),
,
('CA','Canada',true,false,38,true),
,
('CC','Cocos Islands',true,false,39,true),
,
('CD','DR Congo',true,false,40,true),
,
('CF','Central African Republic',true,false,41,true),
,
('CG','Congo',true,false,42,true),
,
('CH','Switzerland',true,false,43,true),
,
('CI','Cote d''Ivoire',true,false,44,true),
,
('CK','Cook Islands',true,false,45,true),
,
('CL','Chile',true,false,46,true),
,
('CM','Cameroon',true,false,47,true),
,
('CN','China',true,false,48,true),
,
('CO','Colombia',true,false,49,true),
,
('CR','Costa Rica',true,false,50,true)
on conflict (code) do update set
  is_active = true,
  league_enabled = true,
  sort_order = coalesce(public.geo_countries.sort_order, excluded.sort_order);
