insert into public.geo_countries (code, name, is_active, profile_enabled, sort_order, league_enabled)
values
,
('MR','Mauritania',true,false,151,true),
,
('MS','Montserrat',true,false,152,true),
,
('MT','Malta',true,false,153,true),
,
('MU','Mauritius',true,false,154,true),
,
('MV','Maldives',true,false,155,true),
,
('MW','Malawi',true,false,156,true),
,
('MX','Mexico',true,false,157,true),
,
('MY','Malaysia',true,false,158,true),
,
('MZ','Mozambique',true,false,159,true),
,
('NA','Namibia',true,false,160,true),
,
('NC','New Caledonia',true,false,161,true),
,
('NE','Niger',true,false,162,true),
,
('NF','Norfolk Island',true,false,163,true),
,
('NG','Nigeria',true,false,164,true),
,
('NI','Nicaragua',true,false,165,true),
,
('NL','Netherlands',true,false,166,true),
,
('NO','Norway',true,false,167,true),
,
('NP','Nepal',true,false,168,true),
,
('NR','Nauru',true,false,169,true),
,
('NU','Niue',true,false,170,true),
,
('NZ','New Zealand',true,false,171,true),
,
('OM','Oman',true,false,172,true),
,
('PA','Panama',true,false,173,true),
,
('PE','Peru',true,false,174,true),
,
('PF','French Polynesia',true,false,175,true),
,
('PG','Papua New Guinea',true,false,176,true),
,
('PH','Philippines',true,false,177,true),
,
('PK','Pakistan',true,false,178,true),
,
('PL','Poland',true,false,179,true),
,
('PM','Saint Pierre and Miquelon',true,false,180,true),
,
('PN','Pitcairn',true,false,181,true),
,
('PR','Puerto Rico',true,false,182,true),
,
('PS','Palestine',true,false,183,true),
,
('PT','Portugal',true,false,184,true),
,
('PW','Palau',true,false,185,true),
,
('PY','Paraguay',true,false,186,true),
,
('QA','Qatar',true,false,187,true),
,
('RE','Reunion',true,false,188,true),
,
('RO','Romania',true,false,189,true),
,
('RS','Serbia',true,false,190,true),
,
('RU','Russia',true,false,191,true),
,
('RW','Rwanda',true,false,192,true),
,
('SA','Saudi Arabia',true,false,193,true),
,
('SB','Solomon Islands',true,false,194,true),
,
('SC','Seychelles',true,false,195,true),
,
('SD','Sudan',true,false,196,true),
,
('SE','Sweden',true,false,197,true),
,
('SG','Singapore',true,false,198,true),
,
('SH','Saint Helena',true,false,199,true),
,
('SI','Slovenia',true,false,200,true)
on conflict (code) do update set
  is_active = true,
  league_enabled = true,
  sort_order = coalesce(public.geo_countries.sort_order, excluded.sort_order);
