insert into public.geo_countries (code, name, is_active, profile_enabled, sort_order, league_enabled)
values
,
('SJ','Svalbard and Jan Mayen',true,false,201,true),
,
('SK','Slovakia',true,false,202,true),
,
('SL','Sierra Leone',true,false,203,true),
,
('SM','San Marino',true,false,204,true),
,
('SN','Senegal',true,false,205,true),
,
('SO','Somalia',true,false,206,true),
,
('SR','Suriname',true,false,207,true),
,
('SS','South Sudan',true,false,208,true),
,
('ST','Sao Tome and Principe',true,false,209,true),
,
('SV','El Salvador',true,false,210,true),
,
('SX','Sint Maarten',true,false,211,true),
,
('SY','Syria',true,false,212,true),
,
('SZ','Eswatini',true,false,213,true),
,
('TC','Turks and Caicos Islands',true,false,214,true),
,
('TD','Chad',true,false,215,true),
,
('TF','French Southern Territories',true,false,216,true),
,
('TG','Togo',true,false,217,true),
,
('TH','Thailand',true,false,218,true),
,
('TJ','Tajikistan',true,false,219,true),
,
('TK','Tokelau',true,false,220,true),
,
('TL','Timor-Leste',true,false,221,true),
,
('TM','Turkmenistan',true,false,222,true),
,
('TN','Tunisia',true,false,223,true),
,
('TO','Tonga',true,false,224,true),
,
('TR','Turkiye',true,true,225,true),
,
('TT','Trinidad and Tobago',true,false,226,true),
,
('TV','Tuvalu',true,false,227,true),
,
('TW','Taiwan',true,false,228,true),
,
('TZ','Tanzania',true,false,229,true),
,
('UA','Ukraine',true,false,230,true),
,
('UG','Uganda',true,false,231,true),
,
('UM','US Minor Outlying Islands',true,false,232,true),
,
('US','United States',true,false,233,true),
,
('UY','Uruguay',true,false,234,true),
,
('UZ','Uzbekistan',true,false,235,true),
,
('VA','Vatican City',true,false,236,true),
,
('VC','Saint Vincent and the Grenadines',true,false,237,true),
,
('VE','Venezuela',true,false,238,true),
,
('VG','British Virgin Islands',true,false,239,true),
,
('VI','US Virgin Islands',true,false,240,true),
,
('VN','Vietnam',true,false,241,true),
,
('VU','Vanuatu',true,false,242,true),
,
('WF','Wallis and Futuna',true,false,243,true),
,
('WS','Samoa',true,false,244,true),
,
('YE','Yemen',true,false,245,true),
,
('YT','Mayotte',true,false,246,true),
,
('ZA','South Africa',true,false,247,true),
,
('ZM','Zambia',true,false,248,true),
,
('ZW','Zimbabwe',true,false,249,true)
on conflict (code) do update set
  is_active = true,
  league_enabled = true,
  sort_order = coalesce(public.geo_countries.sort_order, excluded.sort_order);
