-- ISO 3166-1 alpha-2 seed (249)
-- Mevcut satÄ±rlarÄ±n name / profile_enabled deÄŸerleri korunur.
insert into public.geo_countries (code, name, is_active, profile_enabled, sort_order, league_enabled)
values
('AD','Andorra',true,false,1,true),
('AE','United Arab Emirates',true,false,2,true),
('AF','Afghanistan',true,false,3,true),
('AG','Antigua and Barbuda',true,false,4,true),
('AI','Anguilla',true,false,5,true),
('AL','Albania',true,false,6,true),
('AM','Armenia',true,false,7,true),
('AO','Angola',true,false,8,true),
('AQ','Antarctica',true,false,9,true),
('AR','Argentina',true,false,10,true),
('AS','American Samoa',true,false,11,true),
('AT','Austria',true,false,12,true),
('AU','Australia',true,false,13,true),
('AW','Aruba',true,false,14,true),
('AX','Aland Islands',true,false,15,true),
('AZ','Azerbaijan',true,false,16,true),
('BA','Bosnia and Herzegovina',true,false,17,true),
('BB','Barbados',true,false,18,true),
('BD','Bangladesh',true,false,19,true),
('BE','Belgium',true,false,20,true),
('BF','Burkina Faso',true,false,21,true),
('BG','Bulgaria',true,false,22,true),
('BH','Bahrain',true,false,23,true),
('BI','Burundi',true,false,24,true),
('BJ','Benin',true,false,25,true),
('BL','Saint Barthelemy',true,false,26,true),
('BM','Bermuda',true,false,27,true),
('BN','Brunei',true,false,28,true),
('BO','Bolivia',true,false,29,true),
('BQ','Caribbean Netherlands',true,false,30,true),
('BR','Brazil',true,false,31,true),
('BS','Bahamas',true,false,32,true),
('BT','Bhutan',true,false,33,true),
('BV','Bouvet Island',true,false,34,true),
('BW','Botswana',true,false,35,true),
('BY','Belarus',true,false,36,true),
('BZ','Belize',true,false,37,true),
('CA','Canada',true,false,38,true),
('CC','Cocos Islands',true,false,39,true),
('CD','DR Congo',true,false,40,true),
('CF','Central African Republic',true,false,41,true),
('CG','Congo',true,false,42,true),
('CH','Switzerland',true,false,43,true),
('CI','Cote d''Ivoire',true,false,44,true),
('CK','Cook Islands',true,false,45,true),
('CL','Chile',true,false,46,true),
('CM','Cameroon',true,false,47,true),
('CN','China',true,false,48,true),
('CO','Colombia',true,false,49,true),
('CR','Costa Rica',true,false,50,true),
('CU','Cuba',true,false,51,true),
('CV','Cabo Verde',true,false,52,true),
('CW','Curacao',true,false,53,true),
('CX','Christmas Island',true,false,54,true),
('CY','Cyprus',true,false,55,true),
('CZ','Czechia',true,false,56,true),
('DE','Germany',true,false,57,true),
('DJ','Djibouti',true,false,58,true),
('DK','Denmark',true,false,59,true),
('DM','Dominica',true,false,60,true),
('DO','Dominican Republic',true,false,61,true),
('DZ','Algeria',true,false,62,true),
('EC','Ecuador',true,false,63,true),
('EE','Estonia',true,false,64,true),
('EG','Egypt',true,false,65,true),
('EH','Western Sahara',true,false,66,true),
('ER','Eritrea',true,false,67,true),
('ES','Spain',true,false,68,true),
('ET','Ethiopia',true,false,69,true),
('FI','Finland',true,false,70,true),
('FJ','Fiji',true,false,71,true),
('FK','Falkland Islands',true,false,72,true),
('FM','Micronesia',true,false,73,true),
('FO','Faroe Islands',true,false,74,true),
('FR','France',true,false,75,true),
('GA','Gabon',true,false,76,true),
('GB','United Kingdom',true,false,77,true),
('GD','Grenada',true,false,78,true),
('GE','Georgia',true,false,79,true),
('GF','French Guiana',true,false,80,true),
('GG','Guernsey',true,false,81,true),
('GH','Ghana',true,false,82,true),
('GI','Gibraltar',true,false,83,true),
('GL','Greenland',true,false,84,true),
('GM','Gambia',true,false,85,true),
('GN','Guinea',true,false,86,true),
('GP','Guadeloupe',true,false,87,true),
('GQ','Equatorial Guinea',true,false,88,true),
('GR','Greece',true,false,89,true),
('GS','South Georgia',true,false,90,true),
('GT','Guatemala',true,false,91,true),
('GU','Guam',true,false,92,true),
('GW','Guinea-Bissau',true,false,93,true),
('GY','Guyana',true,false,94,true),
('HK','Hong Kong',true,false,95,true),
('HM','Heard Island',true,false,96,true),
('HN','Honduras',true,false,97,true),
('HR','Croatia',true,false,98,true),
('HT','Haiti',true,false,99,true),
('HU','Hungary',true,false,100,true),
('ID','Indonesia',true,false,101,true),
('IE','Ireland',true,false,102,true),
('IL','Israel',true,false,103,true),
('IM','Isle of Man',true,false,104,true),
('IN','India',true,false,105,true),
('IO','British Indian Ocean Territory',true,false,106,true),
('IQ','Iraq',true,false,107,true),
('IR','Iran',true,false,108,true),
('IS','Iceland',true,false,109,true),
('IT','Italy',true,false,110,true),
('JE','Jersey',true,false,111,true),
('JM','Jamaica',true,false,112,true),
('JO','Jordan',true,false,113,true),
('JP','Japan',true,false,114,true),
('KE','Kenya',true,false,115,true),
('KG','Kyrgyzstan',true,false,116,true),
('KH','Cambodia',true,false,117,true),
('KI','Kiribati',true,false,118,true),
('KM','Comoros',true,false,119,true),
('KN','Saint Kitts and Nevis',true,false,120,true),
('KP','North Korea',true,false,121,true),
('KR','South Korea',true,false,122,true),
('KW','Kuwait',true,false,123,true),
('KY','Cayman Islands',true,false,124,true),
('KZ','Kazakhstan',true,false,125,true),
('LA','Laos',true,false,126,true),
('LB','Lebanon',true,false,127,true),
('LC','Saint Lucia',true,false,128,true),
('LI','Liechtenstein',true,false,129,true),
('LK','Sri Lanka',true,false,130,true),
('LR','Liberia',true,false,131,true),
('LS','Lesotho',true,false,132,true),
('LT','Lithuania',true,false,133,true),
('LU','Luxembourg',true,false,134,true),
('LV','Latvia',true,false,135,true),
('LY','Libya',true,false,136,true),
('MA','Morocco',true,false,137,true),
('MC','Monaco',true,false,138,true),
('MD','Moldova',true,false,139,true),
('ME','Montenegro',true,false,140,true),
('MF','Saint Martin',true,false,141,true),
('MG','Madagascar',true,false,142,true),
('MH','Marshall Islands',true,false,143,true),
('MK','North Macedonia',true,false,144,true),
('ML','Mali',true,false,145,true),
('MM','Myanmar',true,false,146,true),
('MN','Mongolia',true,false,147,true),
('MO','Macao',true,false,148,true),
('MP','Northern Mariana Islands',true,false,149,true),
('MQ','Martinique',true,false,150,true),
('MR','Mauritania',true,false,151,true),
('MS','Montserrat',true,false,152,true),
('MT','Malta',true,false,153,true),
('MU','Mauritius',true,false,154,true),
('MV','Maldives',true,false,155,true),
('MW','Malawi',true,false,156,true),
('MX','Mexico',true,false,157,true),
('MY','Malaysia',true,false,158,true),
('MZ','Mozambique',true,false,159,true),
('NA','Namibia',true,false,160,true),
('NC','New Caledonia',true,false,161,true),
('NE','Niger',true,false,162,true),
('NF','Norfolk Island',true,false,163,true),
('NG','Nigeria',true,false,164,true),
('NI','Nicaragua',true,false,165,true),
('NL','Netherlands',true,false,166,true),
('NO','Norway',true,false,167,true),
('NP','Nepal',true,false,168,true),
('NR','Nauru',true,false,169,true),
('NU','Niue',true,false,170,true),
('NZ','New Zealand',true,false,171,true),
('OM','Oman',true,false,172,true),
('PA','Panama',true,false,173,true),
('PE','Peru',true,false,174,true),
('PF','French Polynesia',true,false,175,true),
('PG','Papua New Guinea',true,false,176,true),
('PH','Philippines',true,false,177,true),
('PK','Pakistan',true,false,178,true),
('PL','Poland',true,false,179,true),
('PM','Saint Pierre and Miquelon',true,false,180,true),
('PN','Pitcairn',true,false,181,true),
('PR','Puerto Rico',true,false,182,true),
('PS','Palestine',true,false,183,true),
('PT','Portugal',true,false,184,true),
('PW','Palau',true,false,185,true),
('PY','Paraguay',true,false,186,true),
('QA','Qatar',true,false,187,true),
('RE','Reunion',true,false,188,true),
('RO','Romania',true,false,189,true),
('RS','Serbia',true,false,190,true),
('RU','Russia',true,false,191,true),
('RW','Rwanda',true,false,192,true),
('SA','Saudi Arabia',true,false,193,true),
('SB','Solomon Islands',true,false,194,true),
('SC','Seychelles',true,false,195,true),
('SD','Sudan',true,false,196,true),
('SE','Sweden',true,false,197,true),
('SG','Singapore',true,false,198,true),
('SH','Saint Helena',true,false,199,true),
('SI','Slovenia',true,false,200,true),
('SJ','Svalbard and Jan Mayen',true,false,201,true),
('SK','Slovakia',true,false,202,true),
('SL','Sierra Leone',true,false,203,true),
('SM','San Marino',true,false,204,true),
('SN','Senegal',true,false,205,true),
('SO','Somalia',true,false,206,true),
('SR','Suriname',true,false,207,true),
('SS','South Sudan',true,false,208,true),
('ST','Sao Tome and Principe',true,false,209,true),
('SV','El Salvador',true,false,210,true),
('SX','Sint Maarten',true,false,211,true),
('SY','Syria',true,false,212,true),
('SZ','Eswatini',true,false,213,true),
('TC','Turks and Caicos Islands',true,false,214,true),
('TD','Chad',true,false,215,true),
('TF','French Southern Territories',true,false,216,true),
('TG','Togo',true,false,217,true),
('TH','Thailand',true,false,218,true),
('TJ','Tajikistan',true,false,219,true),
('TK','Tokelau',true,false,220,true),
('TL','Timor-Leste',true,false,221,true),
('TM','Turkmenistan',true,false,222,true),
('TN','Tunisia',true,false,223,true),
('TO','Tonga',true,false,224,true),
('TR','Turkiye',true,true,225,true),
('TT','Trinidad and Tobago',true,false,226,true),
('TV','Tuvalu',true,false,227,true),
('TW','Taiwan',true,false,228,true),
('TZ','Tanzania',true,false,229,true),
('UA','Ukraine',true,false,230,true),
('UG','Uganda',true,false,231,true),
('UM','US Minor Outlying Islands',true,false,232,true),
('US','United States',true,false,233,true),
('UY','Uruguay',true,false,234,true),
('UZ','Uzbekistan',true,false,235,true),
('VA','Vatican City',true,false,236,true),
('VC','Saint Vincent and the Grenadines',true,false,237,true),
('VE','Venezuela',true,false,238,true),
('VG','British Virgin Islands',true,false,239,true),
('VI','US Virgin Islands',true,false,240,true),
('VN','Vietnam',true,false,241,true),
('VU','Vanuatu',true,false,242,true),
('WF','Wallis and Futuna',true,false,243,true),
('WS','Samoa',true,false,244,true),
('YE','Yemen',true,false,245,true),
('YT','Mayotte',true,false,246,true),
('ZA','South Africa',true,false,247,true),
('ZM','Zambia',true,false,248,true),
('ZW','Zimbabwe',true,false,249,true)
on conflict (code) do update set
  is_active = true,
  league_enabled = true,
  sort_order = coalesce(public.geo_countries.sort_order, excluded.sort_order);

-- Keep TR display name
update public.geo_countries set name = 'Turkiye' where code = 'TR' and name is distinct from 'Turkiye';
-- Prefer existing Turkish UI name if already Turkiye/Türkiye
update public.geo_countries set name = 'Türkiye' where code = 'TR';
