-- Premium oda arka plan temaları (client OdaTemaKatalogu ile uyumlu — 52 tasarım)

insert into public.room_themes (code, name, sort_order) values
  ('midnight_plum', 'Gece eriği', 1),
  ('neon_aurora', 'Neon aurora', 2),
  ('royal_gold', 'Kraliyet', 3),
  ('cosmic_void', 'Kozmik', 4),
  ('arctic_mist', 'Arktik', 5),
  ('cherry_noir', 'Kiraz noir', 6),
  ('emerald_haze', 'Zümrüt', 7),
  ('sunset_pulse', 'Gün batımı', 8),
  ('electric_lilac', 'Elektrik', 9),
  ('ocean_depth', 'Okyanus', 10),
  ('velvet_rose', 'Kadife gül', 11),
  ('cyber_mint', 'Siber mint', 12),
  ('obsidian_noir', 'Obsidyen', 13),
  ('amethyst_dusk', 'Ametist alacakaranlık', 14),
  ('noir_sapphire', 'Noir safir', 15),
  ('graphite_smoke', 'Grafit duman', 16),
  ('indigo_velvet', 'Indigo kadife', 17),
  ('plasma_pink', 'Plazma pembe', 18),
  ('laser_violet', 'Lazer mor', 19),
  ('hologram_teal', 'Hologram teal', 20),
  ('neon_citrus', 'Neon turunç', 21),
  ('synthwave_dusk', 'Synthwave', 22),
  ('volt_blue', 'Volt mavi', 23),
  ('champagne_suite', 'Şampanya süit', 24),
  ('black_diamond', 'Siyah elmas', 25),
  ('platinum_lounge', 'Platin lounge', 26),
  ('amber_throne', 'Kehribar taht', 27),
  ('ruby_vip', 'Yakut VIP', 28),
  ('jade_palace', 'Yeşim saray', 29),
  ('forest_whisper', 'Orman fısıltısı', 30),
  ('lagoon_breeze', 'Lagün esintisi', 31),
  ('moss_temple', 'Yosun tapınak', 32),
  ('glacier_peak', 'Buzul zirve', 33),
  ('desert_mirage', 'Çöl serabı', 34),
  ('tropical_night', 'Tropik gece', 35),
  ('blush_satin', 'Allık saten', 36),
  ('crimson_silk', 'Kızıl ipek', 37),
  ('peach_glow', 'Şeftali ışıltı', 38),
  ('lavender_dream', 'Lavanta rüya', 39),
  ('bordeaux_night', 'Bordo gece', 40),
  ('nebula_rose', 'Nebula gül', 41),
  ('starlight_indigo', 'Yıldız indigo', 42),
  ('galaxy_teal', 'Galaksi teal', 43),
  ('pulsar_purple', 'Pulsar mor', 44),
  ('comet_trail', 'Kuyruklu yıldız', 45),
  ('void_ember', 'Boşluk koru', 46),
  ('chrome_frost', 'Krom buz', 47),
  ('copper_wire', 'Bakır tel', 48),
  ('titanium_edge', 'Titanyum kenar', 49),
  ('bronze_mirror', 'Bronz ayna', 50),
  ('mercury_glass', 'Cıva cam', 51),
  ('steel_neon', 'Çelik neon', 52)
on conflict (code) do update
  set name = excluded.name,
      sort_order = excluded.sort_order,
      is_active = true;
