-- Premium oda görünüm / düzen tasarımları (client OdaDuzeniniCoz ile uyumlu — 40 tasarım)

insert into public.room_layouts (code, name, description, sort_order) values
  ('floating_glass', 'Cam yüzer', 'Cam ızgara · soft halo', 1),
  ('aurora_stage', 'Aurora sahne', 'Spot ışık · 3 kolon', 2),
  ('orbit', 'Yörünge', 'Merkez taht · yay yerleşim', 3),
  ('royal_lounge', 'Kraliyet salonu', 'VIP salon · geniş koltuk', 4),
  ('cosmic', 'Kozmik', 'Yoğun hex ızgara', 5),
  ('minimal_stage', 'Minimal sahne', 'İkili odak · sade', 6),
  ('spotlight_pro', 'Spot Pro', 'Dev taht · yan destek', 7),
  ('theater_gold', 'Altın tiyatro', 'Geniş sahne · altın aura', 8),
  ('podium_elite', 'Elit podyum', 'Premium podyum sahne', 9),
  ('arena_crown', 'Arena taç', 'İki kanat · merkez taht', 10),
  ('grand_stage', 'Büyük sahne', 'Geniş tiyatro sahnesi', 11),
  ('cinematic_wide', 'Sinematik', 'Geniş kadraj · 5 kolon', 12),
  ('lattice_pro', 'Kafes Pro', 'Dengeli premium ızgara', 13),
  ('crystal_grid', 'Kristal ızgara', 'Cam kristal dizilim', 14),
  ('neon_matrix', 'Neon matris', 'Yoğun neon hex', 15),
  ('soft_mosaic', 'Yumuşak mozaik', '3 kolon · büyük avatar', 16),
  ('premium_tiles', 'Premium karo', 'VIP karo ızgara', 17),
  ('hex_pulse', 'Hex nabız', '5 kolon nabız dizilim', 18),
  ('galaxy_ring', 'Galaksi halka', 'Kozmik yörünge halkası', 19),
  ('planet_orbit', 'Gezegen yörünge', 'Orbital mikrofon halkası', 20),
  ('lunar_circle', 'Ay çemberi', 'Ay ışığı daire', 21),
  ('star_wheel', 'Yıldız çarkı', 'Yıldız tekerlek düzeni', 22),
  ('comet_arc', 'Kuyruklu yay', 'Kademeli kuyruk yayı', 23),
  ('velvet_lounge', 'Kadife salon', 'Romantik VIP salon', 24),
  ('champagne_bar', 'Şampanya bar', 'Lounge bar düzeni', 25),
  ('nightclub_booth', 'Kulüp booth', 'Gece kulübü koltuk', 26),
  ('sofa_circle', 'Kanepe çember', 'Sohbet çemberi', 27),
  ('vip_rail', 'VIP ray', 'Yatay VIP mikrofon rayı', 28),
  ('ruby_salon', 'Yakut salon', 'Kırmızı VIP salon', 29),
  ('glass_cascade', 'Cam kademe', 'Kademeli cam dizilim', 30),
  ('diamond_cut', 'Elmas kesim', 'Elmas satır yerleşimi', 31),
  ('asymmetric_wave', 'Asimetrik dalga', 'Dalgalı modern satır', 32),
  ('duo_spotlight', 'İkili spot', 'İkili büyük odak', 33),
  ('prism_stack', 'Prizma yığın', 'Prizma elmas katman', 34),
  ('halo_frame', 'Halo çerçeve', 'Halo halkalı yörünge', 35),
  ('mini_cluster', 'Mini küme', 'Kompakt küme ızgara', 36),
  ('intimate_duo', 'Samimi ikili', 'Flört · yakın ikili', 37),
  ('focus_pair', 'Odak çifti', 'İki kişilik odak', 38),
  ('tight_hex', 'Sıkı hex', 'Yoğun kompakt hex', 39),
  ('whisper_circle', 'Fısıltı çember', 'Küçük sohbet çemberi', 40)
on conflict (code) do update
  set name = excluded.name,
      description = excluded.description,
      sort_order = excluded.sort_order,
      is_active = true;
